config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :trees do
      resources :bubbles
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bubble.rb
class Bubble < ApplicationRecord
  belongs_to :tree
  belongs_to :parent, class_name: :Bubble, :foreign_key => "parent_id", optional: true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/tree.rb
class Tree < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bubbles_controller.rb
class BubblesController < ApplicationController
  before_action :set_bubble, only: [:show, :edit, :update, :destroy]
  before_action :set_instance_variables
  before_action :set_bubbles, only: [:index, :new, :edit]

  # GET /bubbles
  # GET /bubbles.json
  def index
  end

  # GET /bubbles/1
  # GET /bubbles/1.json
  def show
  end

  # GET /bubbles/new
  def new
    @bubble = Bubble.new
  end

  # GET /bubbles/1/edit
  def edit
  end

  # POST /bubbles
  # POST /bubbles.json
  def create
    binding.pry
    @bubble = Bubble.new(bubble_params)

    respond_to do |format|
      if @bubble.save
        format.html { redirect_to [@project, @tree, @bubble], notice: 'Bubble was successfully created.' }
        format.json { render :show, status: :created, location: @bubble }
      else
        format.html { render :new }
        format.json { render json: @bubble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bubbles/1
  # PATCH/PUT /bubbles/1.json
  def update
    respond_to do |format|
      if @bubble.update(bubble_params)
        format.html { redirect_to [@project, @tree, @bubble], notice: 'Bubble was successfully updated.' }
        format.json { render :show, status: :ok, location: @bubble }
      else
        format.html { render :edit }
        format.json { render json: @bubble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bubbles/1
  # DELETE /bubbles/1.json
  def destroy
    @bubble.destroy
    respond_to do |format|
      format.html { redirect_to project_tree_bubbles_url(@project, @tree), notice: 'Bubble was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bubble
      @bubble = Bubble.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bubble_params
      params.require(:bubble).permit(:name, :description, :tree_id, :parent_id)
      .merge(params.permit(:tree_id))
      # # This should probably be cleaned
      # .merge({parent_id: params.require(:parent)})
    end

    def set_instance_variables
      @project = Project.find(params[:project_id])
      @tree = Tree.find(params[:tree_id])
    end

    def set_bubbles
      @bubbles = Bubble.where(tree: @tree)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: [:show, :edit, :update, :destroy]
  before_action :set_instance_variables
  
  # GET /trees
  # GET /trees.json
  def index
    @trees = Tree.all
  end

  # GET /trees/1
  # GET /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees
  # POST /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to project_tree_path(@project, @tree), notice: 'Tree was successfully created.' }
        format.json { render :show, status: :created, location: @tree }
      else
        format.html { render :new }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1
  # PATCH/PUT /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { render :show, status: :ok, location: @tree }
      else
        format.html { render :edit }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1
  # DELETE /trees/1.json
  def destroy
    @tree.destroy
    respond_to do |format|
      format.html { redirect_to project_trees_path(project), notice: 'Tree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tree_params
      params.require(:tree).permit(:name)
      .merge(params.permit(:project_id))
    end

    def project
      Project.find(params[:project_id])
    end

    def set_instance_variables
      @project = project
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bubbles_helper.rb
module BubblesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/bubbles/_form.html.erb
<%= form_with(model: bubble, url: [project, tree, bubble], local: true) do |form| %>
  <% if bubble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bubble.errors.count, "error") %> prohibited this bubble from being saved:</h2>

      <ul>
      <% bubble.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <%= select("bubble",
             "parent_id",
             @bubbles.collect { |b| [b.name, b.id] }, 
             {include_blank: true}) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bubbles/edit.html.erb
<h1>Editing Bubble</h1>

<%= render 'form', bubble: @bubble, project: @project, tree: @tree %>

<%= link_to 'Show', [@project, @tree, @bubble] %> |
<%= link_to 'Back', project_tree_bubbles_path(@project, @tree) %>

app/views/bubbles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bubbles for <%= @tree.name %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bubbles.each do |bubble| %>
      <tr>
        <td><%= bubble.name %></td>
        <td><%= bubble.description %></td>
        <td><%= link_to 'Show', [@project, @tree, bubble] %></td>
        <td><%= link_to 'Edit', edit_project_tree_bubble_path(@project, @tree, bubble) %></td>
        <td><%= link_to 'Destroy', [@project, @tree, bubble], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bubble', new_project_tree_bubble_path(@project, @tree) %>

app/views/bubbles/new.html.erb
<h1>New Bubble</h1>

<%= render 'form', bubble: @bubble, project: @project, tree: @tree %>

<%= link_to 'Back', project_tree_bubbles_path(@project, @tree) %>

app/views/bubbles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bubble.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bubble.description %>
</p>

<p>
  <strong>Tree:</strong>
  <%= @bubble.tree.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @bubble.parent.name %>
</p>


<%= link_to 'Edit', edit_project_tree_bubble_path(@bubble) %> |
<%= link_to 'Back', project_tree_bubbles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BubbleTree</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/trees/_form.html.erb
<%= form_with(model: tree, url: [project, tree], local: true) do |form| %>
  <% if tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
      <% tree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trees/edit.html.erb
<h1>Editing Tree</h1>

<%= render 'form', tree: @tree %>

<%= link_to 'Show', @tree %> |
<%= link_to 'Back', trees_path %>

app/views/trees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trees.each do |tree| %>
      <tr>
        <td><%= tree.name %></td>
        <td><%= tree.project.name %></td>
        <td><%= link_to 'Show', project_tree_path(@project, tree) %></td>
        <td><%= link_to 'Edit', edit_project_tree_path(@project, tree) %></td>
        <td><%= link_to 'Destroy', project_tree_path(@project, tree), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tree', new_project_tree_path(@project) %>

app/views/trees/new.html.erb
<h1>New Tree for project <%= @project.name %></h1>

<%= render 'form', tree: @tree, project: @project %>

<%= link_to 'Back', project_trees_path %>

app/views/trees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tree.name %>
</p>


<%= link_to 'Edit', edit_project_tree_path(@project, @tree) %> |
<%= link_to 'Back', project_trees_path(@project) %>